"""Build gsib_basel_ontology_v1.1.json and ontology/v1.1_review.md from v1.0 + v1.1_additions.yaml.

v1.0 is never modified. Node IDs, hierarchy, names and types are copied verbatim.
"""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "gsib_basel_ontology_v1.0.json"
ADD = ROOT / "ontology" / "v1.1_additions.yaml"
OUT = ROOT / "gsib_basel_ontology_v1.1.json"
REVIEW = ROOT / "ontology" / "v1.1_review.md"


def build() -> dict:
    base = json.loads(SRC.read_text(encoding="utf-8"))
    adds = yaml.safe_load(ADD.read_text(encoding="utf-8"))
    nodes = base["nodes"]
    non_root = [k for k, v in nodes.items() if v.get("parent") is not None]

    unknown = sorted(set(adds) - set(nodes))
    missing = sorted(set(non_root) - set(adds))
    if unknown or missing:
        sys.exit(f"additions mismatch: unknown={unknown} missing={missing}")

    out = copy.deepcopy(base)
    out["ontology"]["version"] = "1.1.0"
    out["ontology"]["changes_from"] = "1.0.0"
    out["ontology"]["changes"] = (
        "Adds per-node label, yes_no_question and criteria{true,false}, and appends exclusions "
        "for known hard boundaries. Node IDs, hierarchy, names and types are unchanged."
    )
    for nid in non_root:
        a = adds[nid]
        for f in ("label", "q", "when_true", "when_false"):
            if not isinstance(a.get(f), str) or not a[f].strip():
                sys.exit(f"{nid}: missing '{f}'")
        extra = set(a) - {"label", "q", "when_true", "when_false", "add_excludes"}
        if extra:
            sys.exit(f"{nid}: unknown keys {sorted(extra)}")
        n = out["nodes"][nid]
        n["label"] = a["label"].strip()
        n["yes_no_question"] = a["q"].strip()
        n["criteria"] = {"true": a["when_true"].strip(), "false": a["when_false"].strip()}
        for ex in a.get("add_excludes") or []:
            if ex not in n["excludes"]:
                n["excludes"].append(ex)
    return out


def review(onto: dict) -> str:
    base = json.loads(SRC.read_text(encoding="utf-8"))["nodes"]
    lines = [
        "# Ontology v1.1 review",
        "",
        "Generated by `ontology/build_v1_1.py`. Edit `ontology/v1.1_additions.yaml`, not this file.",
        "Bold = new in v1.1.",
        "",
    ]
    for nid, n in onto["nodes"].items():
        if n.get("parent") is None:
            continue
        depth = nid.count(".")
        lines.append(f"{'#' * min(2 + depth, 5)} `{nid}` · {n['name']} ({n['type']})")
        lines.append("")
        lines.append(f"- Definition: {n['definition']}")
        if n["includes"]:
            lines.append(f"- Includes: {'; '.join(n['includes'])}")
        old_ex = base[nid]["excludes"]
        new_ex = [e for e in n["excludes"] if e not in old_ex]
        if old_ex or new_ex:
            parts = list(old_ex) + [f"**{e}**" for e in new_ex]
            lines.append(f"- Excludes: {'; '.join(parts)}")
        lines.append(f"- **Label:** {n['label']}")
        lines.append(f"- **Question:** {n['yes_no_question']}")
        lines.append(f"- **True:** {n['criteria']['true']}")
        lines.append(f"- **False:** {n['criteria']['false']}")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    onto = build()
    OUT.write_text(json.dumps(onto, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    REVIEW.write_text(review(onto), encoding="utf-8")
    print(f"wrote {OUT.name} and {REVIEW.relative_to(ROOT)}")
