"""Build gsib_basel_ontology_v1.1.json and ontology/v1.1_review.md from ontology/v1.1_nodes.yaml.

ontology/v1.1_nodes.yaml is the editable source. Children are derived from each
node's `parent`, in file order. `merged_from` maps every v1.1 node to the v1.0
nodes it replaces; every v1.0 node must be covered. Keys starting with "_" are
annotations for the review file and are not written to the ontology.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "ontology" / "v1.1_nodes.yaml"
V10 = ROOT / "gsib_basel_ontology_v1.0.json"
OUT = ROOT / "gsib_basel_ontology_v1.1.json"
REVIEW = ROOT / "ontology" / "v1.1_review.md"
FIELDS = ("name", "type", "parent", "question", "definition", "includes", "excludes", "synonyms",
          "yes_no_question", "criteria", "basel", "merged_from")


def build() -> tuple[dict, dict]:
    src = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    v10 = json.loads(V10.read_text(encoding="utf-8"))["nodes"]
    nodes = {}
    for nid, spec in src["nodes"].items():
        unknown = {k for k in spec if not k.startswith("_")} - set(FIELDS)
        if unknown:
            sys.exit(f"{nid}: unknown keys {sorted(unknown)}")
        n = {k: spec[k] for k in FIELDS if k in spec and spec[k] is not None}
        n["children"] = []
        nodes[nid] = n
    for nid, n in nodes.items():
        p = n.get("parent")
        if p:
            if p not in nodes:
                sys.exit(f"{nid}: parent {p} does not exist")
            nodes[p]["children"].append(nid)
    for nid, n in nodes.items():
        if n["type"] == "leaf":
            n.pop("children")
        if n.get("parent") is not None:
            for f in ("yes_no_question", "criteria"):
                if not n.get(f):
                    sys.exit(f"{nid}: missing {f}")
    covered = {m for n in nodes.values() for m in n.get("merged_from", [])}
    if set(v10) - covered or covered - set(v10):
        sys.exit(f"merged_from mismatch: uncovered={sorted(set(v10) - covered)} unknown={sorted(covered - set(v10))}")
    return {"ontology": src["ontology"], "nodes": nodes}, src["nodes"]


def review(onto: dict, src: dict) -> str:
    n_leaf = sum(1 for n in onto["nodes"].values() if n["type"] == "leaf")
    lines = [
        "# Ontology v1.1 review",
        "",
        "Generated by `ontology/build_v1_1.py` from `ontology/v1.1_nodes.yaml` (edit that file, not this one).",
        f"{len(onto['nodes'])} nodes ({n_leaf} leaves), down from 79 (59 leaves) in v1.0.",
        "`term hits` = corpus articles matching the merged v1.0 nodes' characteristic terms and naming a bank "
        "(rough prevalence from `scripts/term_prevalence.py`, not labels).",
        "",
    ]
    for nid, n in onto["nodes"].items():
        if n.get("parent") is None:
            continue
        depth = nid.count(".")
        merged = n.get("merged_from", [])
        tag = "" if merged == [nid] else f" · **merged from** {', '.join(f'`{m}`' for m in merged)}"
        lines.append(f"{'#' * min(2 + depth, 5)} `{nid}` · {n['name']} ({n['type']}){tag}")
        lines.append("")
        hits = src[nid].get("_term_hits_with_bank")
        if hits is not None:
            lines.append(f"- Term hits: {hits:,}")
        lines.append(f"- Definition: {n['definition']}")
        if n["includes"]:
            lines.append(f"- Includes: {'; '.join(n['includes'])}")
        if n["excludes"]:
            lines.append(f"- Excludes: {'; '.join(n['excludes'])}")
        lines.append(f"- **Question:** {n['yes_no_question']}")
        lines.append(f"- **True:** {n['criteria']['true']}")
        lines.append(f"- **False:** {n['criteria']['false']}")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    onto, src = build()
    OUT.write_text(json.dumps(onto, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    REVIEW.write_text(review(onto, src), encoding="utf-8")
    print(f"wrote {OUT.name} ({len(onto['nodes'])} nodes) and {REVIEW.relative_to(ROOT)}")
